[tool.poetry]
name = "termwiki"
version = "0.2.0"
description = "Personal knowledge management tool for the terminal, with a focus on zero-thought, zero-wait when getting to the bit you're interested in."
authors = ["Gilad Barnea <giladbrn@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.0.3"
fuzzysearch = { version = "^0.7.3", optional = true }
Pygments = "^2.10.0"
rich = "^12"
more-termcolor = "^1.1.3"
# prompt-toolkit = "latest"
# pytest = "^7.1.2"
#lark = { path = "../lark", develop=true }
# markdown-it-py = { path ="../markdown-it-py", develop=true }
types-Pygments = "^2.13.0"

[tool.poetry.scripts]
tw = 'termwiki.cli:main'

[tool.poetry.build]
generate-setup-file = true

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
ipython = "^8.4.0"
ipython-autoimport = "^0.4"
#astload = "^0" # tree from ast.dump. what about ast.unparse?
#asteria = "^0" # 'parentize' for .left .parent .child etc
#astroid = "latest" # patches ast for inference
#asttokens = "latest" # get_text(), .last_token, .first_token
#astor = "latest"
pdbpp = { path = "../pdbpp/", develop = true, optional = true }
pytest-cov = "^3.0.0"
appmap = { version = "^1.5.1", optional = true }
black = {version = "^22.6.0", optional = true}

[tool.black]
line-length = 90
include = '\.pyi?$'
extend-exclude = '''
(
  /test/data/
  | /private_pages/
)
'''


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
