[tool.poetry]
name = "termwiki"
version = "0.2.0"
description = "Personal knowledge management tool for the terminal, with a focus on zero-thought, zero-wait when getting to the bit you're interested in."
authors = ["Gilad Barnea <giladbrn@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
click = "^8.0.3"
fuzzysearch = "^0.7.3"
Pygments = "^2.10.0"
rich = "^12"
more-termcolor = "^1.1.3"
prompt-toolkit = "latest"
pytest = "^7.1.2"
#lark = { path = "../lark", develop=true }
markdown-it-py = { path ="../markdown-it-py", develop=true }

[tool.poetry.scripts]
tw = 'termwiki.cli:main'

[tool.poetry.build]
generate-setup-file = true

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
ipython = "^8.4.0"
ipython-autoimport = "^0.4"
ast-magic = "^1.0.1"
pdbpp = { path = "../pdbpp/", develop = true, optional = true }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
